on: 
  push:
    branches: [main]

jobs:
  build_current:
    name: Build current
    runs-on: ubuntu-latest
    container: python:3
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'
    - name: Install pre-requisites
      run: pip install -r requirements.txt
    - name: Build
      run: mkdocs build -v --clean
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: site-current
        path: ./site
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build_current]
    steps:
    - name: Download current
      uses: actions/download-artifact@v1
      with:
        name: site-current
        path: ./site
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
